export const ERROR_CODE = {
  IMPOSSIBLE_CARD_PAY_TYPE_STORE: 'IMPOSSIBLE_CARD_PAY_TYPE_STORE',
  IMPOSSIBLE_CASH_PAY_TYPE: 'IMPOSSIBLE_CASH_PAY_TYPE',
  IMPOSSIBLE_PREPAID: 'IMPOSSIBLE_PREPAID',
  INCORRECT_STORE_INFO_SETTING: 'INCORRECT_STORE_INFO_SETTING',
  INSUFFICIENT_RIDER_BAROMONEY: 'INSUFFICIENT_RIDER_BAROMONEY',
  INVALID_GOODS_PAY_TYPE: 'INVALID_GOODS_PAY_TYPE',
  INVALID_GOODS_PAY_TYPE_ONLY_PREPAID: 'INVALID_GOODS_PAY_TYPE_ONLY_PREPAID',
  INVALID_GOODS_PAY_TYPE_ONLY_PREPAID_OR_CARD: 'INVALID_GOODS_PAY_TYPE_ONLY_PREPAID_OR_CARD',
  INVALID_STATUS: 'INVALID_STATUS',
  MAINTENANCE_TIME: 'MAINTENANCE_TIME',
  NOT_ALLOW_EXTERNAL: 'NOT_ALLOW_EXTERNAL',
  NOT_ALLOW: 'NOT_ALLOW',
};
