query orderAgencies {
  orderAgencies {
    orderAgencyId
    orderAgencyName
    orderAgencyRejectTime
    orderAgencyPhone
    isClientMappable
    isClientOrderCancelable
    isManageStoreOnOff
    isManageStoreProductSales
    reservedOrderDisplayTime
    orderAgencyType
    createdAt
    updatedAt
  }
}
