query storesByBusinessNumberAndPhone($where: StoresCondition, $orderOption: [[String]]) {
  storesByBusinessNumberAndPhone(where: $where, orderOption: $orderOption) {
    storeId
    storeType
    name
    phone
    ownerPhone
    jibunAddress
    roadAddress
    detailAddress
    location {
      latitude
      longitude
    }
    productPrepareTime
    ownerName
    businessNumber
    status
    isDeliveryPossible
    manageOrderAgencyId
    countryOfOrigin
    createdAt
    updatedAt
  }
}
